/**
 * PRIME DIRECTIVE - Error Logging Utility
 * 
 * Universal error logging for the FoodTrend application.
 * Mandated by: .agent/PRIME_DIRECTIVE.md - Section 1 (Universal Error Logging)
 * 
 * @module logger
 */

(function (window) {
    'use strict';

    const Logger = {
        /**
         * Log an error to the Prime Directive error logging system
         * 
         * @param {string} category - Error category (css-layout, javascript, build-deploy, integration, system)
         * @param {Object} context - Error context
         * @param {Error} context.error - The error object (if available)
         * @param {string} context.message - Error message
         * @param {string} context.userAction - What the user was doing when error occurred
         * @param {Object} context.additionalData - Any additional context
         */
        logError: function (category, context) {
            const errorData = {
                timestamp: new Date().toISOString(),
                category: category,
                page: window.location.href,
                pathname: window.location.pathname,
                message: context.message || (context.error ? context.error.message : 'Unknown error'),
                stack: context.error ? context.error.stack : null,
                userAction: context.userAction || 'Unknown',
                userAgent: navigator.userAgent,
                viewport: {
                    width: window.innerWidth,
                    height: window.innerHeight
                },
                additionalData: context.additionalData || {}
            };

            // Log to console in development
            if (this._isDevelopment()) {
                console.group(`[Prime Directive] Error Logged: ${category}`);
                console.error(errorData);
                console.groupEnd();
            }

            // Store in localStorage for later retrieval
            this._storeError(errorData);

            // Send to server (if endpoint configured)
            this._sendToServer(errorData);

            return errorData;
        },

        /**
         * Retrieve logged errors from localStorage
         * 
         * @param {string} category - Optional category filter
         * @returns {Array} Array of logged errors
         */
        getErrors: function (category) {
            try {
                const errors = JSON.parse(localStorage.getItem('primeDirective_errors') || '[]');
                return category ? errors.filter(e => e.category === category) : errors;
            } catch (e) {
                console.warn('[Prime Directive] Failed to retrieve errors from localStorage:', e);
                return [];
            }
        },

        /**
         * Clear logged errors
         * 
         * @param {string} category - Optional category to clear (clears all if not specified)
         */
        clearErrors: function (category) {
            if (!category) {
                localStorage.removeItem('primeDirective_errors');
                return;
            }

            try {
                const errors = this.getErrors();
                const filtered = errors.filter(e => e.category !== category);
                localStorage.setItem('primeDirective_errors', JSON.stringify(filtered));
            } catch (e) {
                console.warn('[Prime Directive] Failed to clear errors:', e);
            }
        },

        /**
         * Export errors as markdown for Prime Directive error logs
         * 
         * @param {Object} errorData - Error data object
         * @returns {string} Markdown formatted error log
         */
        exportAsMarkdown: function (errorData) {
            const date = new Date(errorData.timestamp).toISOString().split('T')[0];
            return `# ${errorData.category} Error - ${date}

## Error Details
- **Timestamp:** ${errorData.timestamp}
- **Page:** ${errorData.page}
- **Message:** ${errorData.message}
- **User Action:** ${errorData.userAction}

## Stack Trace
\`\`\`
${errorData.stack || 'No stack trace available'}
\`\`\`

## Context
- **User Agent:** ${errorData.userAgent}
- **Viewport:** ${errorData.viewport.width}x${errorData.viewport.height}
- **Additional Data:** ${JSON.stringify(errorData.additionalData, null, 2)}

## Root Cause
[To be filled in during investigation]

## Fix Applied
[To be filled in after fix]

## Prevention
[To be filled in - how to avoid in future]

## Automation Created
- [ ] Troubleshooting guide entry
- [ ] Workflow automation
- [ ] Unit test
- [ ] Documentation update

---
*Auto-generated by Prime Directive logger.js*
`;
        },

        // Private methods

        _isDevelopment: function () {
            return window.location.hostname === 'localhost' ||
                window.location.hostname === '127.0.0.1' ||
                window.location.protocol === 'file:';
        },

        _storeError: function (errorData) {
            try {
                const errors = this.getErrors();
                errors.push(errorData);

                // Keep only last 100 errors to avoid localStorage limits
                if (errors.length > 100) {
                    errors.shift();
                }

                localStorage.setItem('primeDirective_errors', JSON.stringify(errors));
            } catch (e) {
                // Graceful fallback if localStorage fails
                console.warn('[Prime Directive] Failed to store error in localStorage:', e);
                console.warn('Original error:', errorData);
            }
        },

        _sendToServer: function (errorData) {
            // TODO: Implement server-side logging endpoint
            // For now, this is a placeholder for future implementation
            const endpoint = window.PRIME_DIRECTIVE_ENDPOINT;

            if (!endpoint) {
                return; // No endpoint configured
            }

            // Send error asynchronously without blocking
            if (navigator.sendBeacon) {
                navigator.sendBeacon(endpoint, JSON.stringify(errorData));
            } else {
                fetch(endpoint, {
                    method: 'POST',
                    headers: { 'Content-Type': 'application/json' },
                    body: JSON.stringify(errorData),
                    keepalive: true
                }).catch(err => {
                    console.warn('[Prime Directive] Failed to send error to server:', err);
                });
            }
        }
    };

    // Setup global error handlers
    Logger.setupGlobalHandlers = function () {
        // Handle uncaught errors
        window.addEventListener('error', function (event) {
            Logger.logError('javascript', {
                error: event.error,
                message: event.message,
                userAction: 'Page runtime',
                additionalData: {
                    filename: event.filename,
                    lineno: event.lineno,
                    colno: event.colno
                }
            });
        });

        // Handle unhandled promise rejections
        window.addEventListener('unhandledrejection', function (event) {
            Logger.logError('javascript', {
                error: event.reason instanceof Error ? event.reason : new Error(String(event.reason)),
                message: 'Unhandled Promise Rejection',
                userAction: 'Async operation',
                additionalData: {
                    reason: String(event.reason)
                }
            });
        });

        console.log('[Prime Directive] Global error handlers installed');
    };

    // Auto-install if in browser environment
    if (typeof window !== 'undefined') {
        window.Logger = Logger;

        // Auto-setup global handlers on DOMContentLoaded
        if (document.readyState === 'loading') {
            document.addEventListener('DOMContentLoaded', function () {
                Logger.setupGlobalHandlers();
            });
        } else {
            Logger.setupGlobalHandlers();
        }
    }

    // Export for module systems
    if (typeof module !== 'undefined' && module.exports) {
        module.exports = Logger;
    }

})(typeof window !== 'undefined' ? window : global);
